### ISSUE TITLE
Error: Extension "table" could not be loaded.

### ISSUE THREAD

**Issue by noahtallen** [xieranmaya/gulp-showdown#7]
When installing `gulp-showdown` for the first time, I get the error in the title. (The error seems to be coming from showdown.js itself, not gulp-showdown.) Commenting out the 'table' extension in the `defaultOptions` variable solves the issue. I have a feeling that something isn't getting installed by default to handle markdown tables that should be. Any clue how to properly resolve this issue?

**Comment by ajaybc** [comment]
I am having the same issue

**Comment by sbergotts** [comment]
for anyone that stumbles here, there is the possibility to avoid this issue by providing an option object:

    gulp.src('src/**/*.md')
        .pipe(gulpShowdown({ extensions: [] }))
        .pipe(gulp.dest('dist'));

**Comment by TeoConan** [comment]
If you need to use tables, please use this answer to enable it
Tables has been moved to core

https://github.com/showdownjs/showdown/issues/945#issuecomment-1205375626
